version: '3.8'

services:

  test_db:
    image: postgres:15.3
    container_name: nekidatem_test_db
    restart: always
    environment:
      - POSTGRES_DB=nekidaem_test_base
      - POSTGRES_USER=test_postgres
      - POSTGRES_PASSWORD=test_postgres
      - DB_HOST=test_db
      - DB_PORT=5432
    ports:
      - 5438:5432
    extra_hosts:
      - "host.docker.internal:host-gateway"
